#! /bin/sh
bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Locale
setxkbmap -option grp:alt_shift_toggle ua,us &

# Auto Start
sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &
picom --config $HOME/.config/bspwm/picom/picom.conf &
dunst -config $HOME/.config/bspwm/dunst/dunstrc &
polybar --config=$HOME/.config/bspwm/polybar/config.ini &
nitrogen --restore 